redisio:
  restart: always
  image: redis:latest
postgresql:
  restart: always
  image: postgres:latest
multistreamer:
  restart: always
  image: jprjr/multistreamer:10.1.1-2
  links:
   - redisio
   - postgresql

